name:                numeration-bases
version:             0.1.0.0
author:              "Alex Ionescu"
maintainer:          "alxi.2001@gmail.com"
copyright:           "Copyright (C) 2019 Alex Ionescu"

dependencies:
- base >= 4.7 && < 5
- parsec

executables:
  numeration-bases-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wincomplete-patterns
    - -Wincomplete-uni-patterns